patch operand image and job image with enviroment variable
IBM/ibm-user-management-operator pull request #32
Opened 2024-07-24 15:06 UTC by qpdpQ

1. add operand image and job image into container env variable
2. patch resource yaml file with those image

2024-07-24 15:58 UTC, Daniel-Fan approved these changes

2024-07-24 15:58 UTC, Daniel-Fan commented
/lgtm

2024-07-24 17:53 UTC, bitscuit requested changes
Missing the cert-rotation image

2024-07-24 18:28 UTC, bitscuit commented on internal/resources/constant/constant.go
> +package constant
this actually should be package `resources` because that's the folder name

2024-07-24 19:31 UTC, bitscuit commented on bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
> +                  value: docker-na-public.artifactory.swg-devops.com/hyc-cloud-private-scratch-docker-local/ibmcom/account-iam-amd64:20240722
can we change these to use the latest tag, and also from integration registry?

2024-07-24 19:31 UTC, bitscuit commented on bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
> +                  value: docker-na-public.artifactory.swg-devops.com/hyc-cloud-private-scratch-docker-local/ibmcom/mcsp-im-config-job-amd64:5796e4d
Can we use the integration registry for these?

2024-07-29 19:25 UTC, Daniel-Fan commented
Hi @qpdpQ 
Could you please help to add two more images for UI?
https://github.com/IBM/ibm-user-management-operator/blob/192494b6d193941e59ad99dad9f5ecb25e98db06/internal/resources/yamls/ui.go#L333
https://github.com/IBM/ibm-user-management-operator/blob/192494b6d193941e59ad99dad9f5ecb25e98db06/internal/resources/yamls/ui.go#L503

2024-07-30 15:04 UTC, closed without merging